// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'details': string;
  'episodeTitle': string;
  'existingFileName': string;
  'fileContext': string;
  'filterInput': string;
  'footer': string;
  'incomingFileName': string;
  'modalBody': string;
  'noFileContext': string;
  'scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
